### PR TITLE
[WIP] React 16 support

### PR DESCRIPTION
**Pull request by sapegin**
* Update peer dependencies to include React 16.
* Disable react-addons-perf (doesn’t support React 16 yet).
* Add Enzyme and rewrite couple of tests (that stopped to work) to use it.

Dnd needs to be fixed.

### CODE REVIEW

**Comment by bebraw** [comment]
Related: https://github.com/react-dnd/react-dnd/issues/896 .

**Comment by bebraw** [comment]
I rebased this at https://github.com/reactabular/reactabular/tree/react16 .

Maybe we merge that, document the gotcha, and publish?

**Comment by sapegin** [comment]
Yeah, sure. There are no regressions, just some stuff won’t work in React 16.

**Comment by bebraw** [comment]
I merged my branch and published as `8.12.0`. Still a few packages to upgrade (easy for one) but we are mostly done here.

**Pull request closed without merging**
