### PR TITLE
React 15.5 upgrade, fixed deprecations

### PR DESCRIPTION
**Pull request by joseds**
This commit removes deprecations regarding React.PropTypes and react-addons-test-utils, see [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html). 

This is a preparation to be able to upgrade to React 16 without further code changes. It also fixes problems I had with Jest snapshot testing when using reactabular with the current React version 15.5.x.

### CODE REVIEW

**Comment by bebraw** [comment]
Looks like there's still something missing. Please fix the CI, rebase, and I'll merge. Thanks. 👍

**Comment by joseds** [comment]
Sorry, I had forgotten to fix some imports, should have run the tests locally before pushing.

**Comment by bebraw** [comment]
No probs. That's why the CI exists. 👍

**Comment by bebraw** [comment]
Any idea about those

> Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types

warnings in **reactabular-table**? We are doing something stupid there, just not exactly sure what. The warning seems to point at https://github.com/reactjs/prop-types/blob/master/README.md#difference-from-reactproptypes-dont-call-validator-functions .

It would be good to fix this before a release.

**Comment by joseds** [comment]
These warnings result from Jest itself, I will do a PR for a Jest upgrade, the current version 19.0.2 has it fixed.

**Pull request merged**
