### PR TITLE
Filtering fix

### PR DESCRIPTION
**Pull request by chiss2906**
- Fixed the columnMatches function, where an empty column property caused wrong search results.
- Performance improvement by making separate functions for default parameters.

### CODE REVIEW

**Comment by bebraw** [comment]
Nice work. Could you add a test case against the faulty behavior so we won't accidentally introduce it again?

**Comment by chiss2906** [comment]
Sorry, I don't feel confident in doing this :)

**Comment by bebraw** [comment]
No probs. I think I'll merge and add the test there. Thanks. 👍

**Comment by bebraw** [comment]
Fixed in `6.1.1`. I didn't figure out a test. If you can give me test input/output against the old version, I don't mind setting it up.

**Pull request merged**
