### PR TITLE
Extract nested column logic from the table

### PR DESCRIPTION
**Pull request by bebraw**
Instead of resolving within table core, it seems more sensible to do it outside of it. The greatest benefit of doing this is that all the logic will just work. Also the core becomes a little simpler as a result while the system remains even more decoupled than before.

I am still in progress of figuring out a good way to integrate the new idea with reactabular-easy. The biggest problem seems to be the split in resolution logic (headers and columns are resolved separately) and binding easy logic to that.

It would be awesome if you could have a look at the initial implementation. I know it's more code to write for the user if you want to use nested definition. But on the plus side this gives a little extra flexibility, fixes the logic, and improves performance a notch (no need to resolve tree always).

Closes #241.

CC @smoke @sapegin

### CODE REVIEW

**Comment by sapegin** [comment]
The API looks good. But what `label` for children columns does?

**Comment by bebraw** [comment]
The children column follow the same definition as the main one. `label` might have to so with this: https://reactabular.js.org/#/column-definition/header . Can you point to a specific line?

**Comment by sapegin** [comment]
I mean this example:

```js
{
          header: {
            label: 'Name'
          },
          children: [
            {
              property: 'name.first',
              header: {
                label: 'First Name'
              },
              cell: {
                format: highlight.cell
              }
            },
            {
              property: 'name.last',
              header: {
                label: 'Last Name'
              },
              cell: {
                format: highlight.cell
              }
            }
          ]
        },
```

When `First Name` and `Last Name` labels will be displayed?

**Comment by bebraw** [comment]
Ah, that. It actually works already. See https://reactabular.js.org/#/column-definition/nested-columns . It performs calculation so that the children will become children of that `Name` portion and will be displayed below it as you might expect.

This PR is about extracting that logic so that sorting/search/etc. work. Instead of having support for the hierarchical columns internal, I will extract it outside so that you can convert.

I have an early idea on how to deal with easy now. The header conversion bit needs to change a little (going to be simpler and faster even).

**Comment by bebraw** [comment]
I think the functionality starts to be there. **reactabular-easy** is starting to get a little gnarly due to drag and drop (very hard with nested data). Maybe I need to relax the problem a bit (flat column definition instead). Even then handling column widths remains a problem. I'm ok by not supporting that feature for now.

It also feels like `easy.bindColumns` could be decomposed into smaller functions now that I have exposed it to the user. The current solution does a little too much at once. Earlier this was hidden but I realized it belongs to the user side as you need more control with more complicated data structures.

Maybe the binding logic belongs outside of **reactabular-easy** even. It provides a nice way to extend the default column schema at least so it feels like a package. Done right you could get these little flags (`header.sortable`, `cell.highlight`) into your table with very minimal effort.

**Comment by bebraw** [comment]
I implemented the bind idea. See [bind](https://github.com/reactabular/reactabular/blob/nested-columns/packages/reactabular-easy/src/bind.js) and [bind-columns](https://github.com/reactabular/reactabular/blob/nested-columns/packages/reactabular-easy/src/bind-columns.js). Maybe this should become a package of its own. At least internally it's far neater right now although it can probably be pushed a notch further. Those binding bits could do some data processing as well perhaps. I'm still a little unsure of that.

To keep it composable I generalized `format` as `formatters` field. This means it accepts an array that gets reduced to a single formatted value. Essentially you get `formatters: [a, b, c]` -> `a(b(c(value, extra))` so you can do nesting (apply highlighting, whatnot on single value). This is a symmetrical API with `transforms` and gives composability given it's possible to `merge` all this. 

Incidentally I ended up using `webpack-merge` here as it does exactly what I want. Perhaps the core algorithm needs to become a separate package as it seems to be useful beyond webpack alone.

**reactabular-easy** header drag and drop feels a little sketchy in nested case but there's not much I can do about that without doing something really special. I gave [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) a go but it didn't scale to the nested case.

The biggest problem is width handling of columns. Currently I retain width per column while dragging to avoid flickering but this isn't particularly cool if you have thin and wide columns in your layout. Moving a wide column to a thin ends up looking bad. It would be better to retain the original widths but handling the detection against flicker at React DnD seems like a hard problem and I don't have a clear solution for that yet.

I still have to try some optimization, write change logs, and merge to master. Feedback is welcome, though.

**Pull request merged**
