### PR TITLE
Enable mobile mode for HtmlWebpackPlugin

### PR DESCRIPTION
**Pull request by sapegin**
Most of the pages are at least readable ;-)

Catalog already supports responsiveness.

### CODE REVIEW

**Comment by bebraw** [comment]
Awesome. Deployed. 👍

**Comment by sapegin** [comment]
Cool, looks good on my iPhone!

**Comment by bebraw** [comment]
How did you figure out that flag? On a quick look I can't see a direct reference to it in the source.

**Comment by sapegin** [comment]
I found it in the template: https://github.com/reactabular/reactabular/blob/master/templates/index.ejs#L14-L16

**Comment by bebraw** [comment]
Ah, yeah. Forgot about that entirely. Thanks. 👍

**Pull request merged**
