### PR TITLE
Add reactabular-sort docs to the site

### PR DESCRIPTION
**Pull request by sapegin**

### CODE REVIEW

**Comment by bebraw** [comment]
It's below `data` category right now. [Here](http://reactabular.js.org/#/data/sorting).

That said, alternative categorization would work for me if we can figure out a better one. "Features" and "Data" feel awfully vague.

**Comment by sapegin** [comment]
Shit, I didn’t find it ;-( But for me drag’n’drop and sorting is very close things, so, yeah, “Data” and “Features” isn’t very clear. Not sure I could divide these two somehow.

**Comment by bebraw** [comment]
Ok, let me think about it. I'll come up with a proposal shortly.

**Comment by sapegin** [comment]
Cool, thanks!

**Comment by bebraw** [comment]
@sapegin Can you [have a look](http://reactabular.js.org/) now?

**Comment by sapegin** [comment]
Yeah, I thinks it’s better! 

(Sorry for a stupid pull request ;-|

**Comment by bebraw** [comment]
No probs. That helped me to improve it. 👍

**Comment by bebraw** [comment]
I think the search portion might go out of the project eventually as the dependency to Reactabular is so light. It will make the docs perhaps a little thinner again, but we'll see.

**Pull request closed without merging**
